---
title: "Mini Project 2: A Meaningful Story About Estimation"
author: "Brody Pinto"
date: "2025-02-14"
---

**Tennis: A Game of Estimation**

One word that comes to me when I think of the game of tennis: perfection. Why do I say that? Maybe it’s because I grew up idolizing Roger Federer and fall closely in line with many of his fans who think he had the ‘peRFect’ game. Maybe it’s because the game itself is an active allegory for life. Or maybe it’s because it’s just you and your opponent out there, creating one of the most pristine competitive situations the world of sports will ever see. What does the victor have over the loser of the contest? Is it skill? Endurance? Passion? Or is it something more quantitative that we can attribute to the basis of statistical estimation? Although all of these do certainly play a role in determining the winner of a tennis contest, my task is to provide some insight into why tennis is a game of estimation.

Let’s start with the most basic parameter a tennis player has to pay attention to: where is my opponent going to hit the ball. At the base of the game, if you know where your opponent is going to hit the ball, you already have a significant leg up against your opponent. Many think that this part of tennis is a guessing game, but in reality (at the highest levels of the sport), it most definitely is not. These top professional players can hit the ball so hard with so much accuracy and spin, that guessing where the ball is going to go will be a death sentence on court. These top players – take Novak Djokovic for example – need to come up with an accurate estimator for where the ball will go even before their opponent makes contact with the ball. 

Do you ever wonder why Djokovic makes playing at the highest level of the sport look so easy? It’s because he has mastered and fine-tuned this estimator to give him the most accurate estimate of where the ball is going. It all comes down to two main random variables: court positioning of the opponent and what their racket take-back looks like.

Let’s dive into court positioning first. Given a random sample of, say, 1000 shots, looking at court positioning as the random variable. The majority of those 1000 shots will go cross-court, based on the geometry of the court (there is the most room for error cross-court since the distance across the court is longer than the distance directly down the line) and the height of the net (which is lowest at the middle of the court). For this random sample, let’s say there are 750 cross-court shots. We could compute the likelihood of the ball getting hit cross-court, but in order to maximize the likelihood, we should also consider the opponent could hit the ball down the line the 250 other times. By just using court positioning, our estimate for where the ball will go has a bias towards the cross-court shot. This is where the opponent’s racket take-back comes into play.

There are two parts of the opponent’s racket take-back: racket-face direction and torso coil. The direction the racket-face is pointing can tell you (most of the time) what type of spin will be on the ball when the opponent is hitting it which, depending on the opponent, can provide information about where the ball will be hit. If the racket-face is open (facing up), the incoming shot will either be a slice or a drop-shot; if the racket-face is closed (facing down), the incoming shot will have topspin. At this point, you might ask: how is the type of spin going to help me estimate where my opponent is going to hit the ball? My simple answer is: it doesn’t… by itself. 

But it can if you consider how your opponent is coiling their torso. Reality check: now we’re getting into the nitty gritty of high-level tennis – keep in mind the best players in the world even have trouble doing this every single shot because it requires such a high degree of focus to do so. Now back into the world of tennis theory: the torso coil and foot positioning also play a role in where the opponent is going to hit the ball. If your opponent is more turned into their take-back, the chances of them hitting the ball down the line are higher.

The racket-face and torso coil can’t really tell you where your opponent is going to hit the ball if they’re good at disguising it – this is where a high degree of variance can come into play, but tennis is a complex sport so you can’t really expect there to be a perfectly consistent estimator for shot location (even with a sample size as large as Rafael Nadal at the French Open). However, combining those two factors and the opponent’s court positioning into one all-encompassing estimator, you can get a very good estimate for where they will hit the ball to.

With all that said, it’s impossible to think about all those random variables every time you’re preparing to hit the ball. It turns out that for the best tennis players in the world, they’ve played the game so many times that “reading” where the opponent is going to hit the ball has just become second nature. With Novak Djokovic, for example, it seems like he knows where the ball is going even before his opponent knows. Can this heightened level of premonition be attributed to Djokovic’s genius mind being able to compute the maximum likelihood estimator of shot location in a matter of milliseconds or has it just become second nature for him through his countless hours of training and competing at the highest level of tennis for almost 20 years? Or maybe these two things are one in the same.

