---
title: "Reflection"
author: "Brody Pinto"
date: "2025-05-04"
format: 
  html:
    embed-resources: true
execute: 
  warning: false
---

Over the course of these five mini-projects throughout this semester in math stat, I've truly honed and deepened my understanding of statistical reasoning -- not just because of their inherent purpose of practicing and exemplifying what we've been learning in class but also because of how they built on one another. Looking back through these projects made me realize how they all work together to paint a rich picture of statistical inference and the under-workings behind dealing with uncertainty. In the moment when I was completing these mini-projects, however, they felt like isolated tasks. The purpose of this reflection essay is to explain some of the key connections that can be drawn between the mini-projects and how they contribute to my understanding of the class as a whole. I think that these mini-projects were designed very well to flow almost seamlessly from theory and simulation to modeling, analysis, and reflection.

Starting with mini-project 1 -- a brief look into sampling distributions of the sample minimum and maximum, it was a great project to highlight the importance (and relative accuracy) of statistical simulation. It was valuable to work through substantial examples of simulating a sampling distribution of the sample min and max for four different probability distributions (Normal, Uniform, Exponential, and Beta), and in the end validate the results of the simulation to the actual theoretical values. This utilization of statistical simulation appeared several more times throughout the semester including mini-project 3 where we used simulation to examine the average interval width and coverage rates of confidence intervals using a binomial distribution. My key takeaway here: don't underestimate the power of simulation.

When it comes to mini-project 2 (my short story about estimation in the game of tennis), I talked a lot about how tennis players constantly make informed estimations of where the ball is going so that they can be there ready to hit it back. Not only does the content and topic of tennis align directly with what we did for mini-project 4, but the Bayesian analysis we did on tennis data also takes into account using information to improve our models. It's important to realize that statistics isn't just theory -- one of the main reasons why I like stats so much more than just straight math -- it allows you to directly apply any prior knowledge you might have about some data to draw meaningful conclusions. The Bayesian framework was eye-opening for me when thinking about the application of estimation in the frequentist framework (which honestly feels a bit clunky with too many assumptions). The applicable nature of statistics -- particularly the flexible nature of Bayesian statistics -- has so many upsides, but it also comes with its drawbacks. Since it's so applicable, so many different fields of science and research use statistics to provide numeric support for the work they're doing. As such, there is so much naive use of statistics out there which is where mini-project 5 comes in.

The reading about p-values was a meaningful read for me because it hit pretty close to home in terms of what it was trying to convey. I've always felt like people just abuse statistics to get what they want -- like a publication in a science journal or getting a good grade on a research paper for biology class. The idea of statistical significance has always been something that I've talked about through my years of education and primarily growing up as a science person. This year has been very insightful to me in terms of finding other ways to do statistical or data science analyses without having to report a p-value with a strict binary cutoff point. I've learned that you can obtain meaningful answers to real-world questions without using the traditional frequentist statistician's formula in the Bayesian tennis analysis. As a whole, reflecting on mini-project 5 and the associated reading has made me realize that my understanding of statistical significance has really matured over time. Mini-project 4 (Bayesian analysis) is just another example of a more nuanced and "colorful" alternative to dichotomous p-value thinking. Going off script a bit here, but my SYE work with visualizing tennis data was instrumental in this deeper and more "colorful" understanding of what statistics and data can be used for.

At the end of the day, we're all just trying to tell a story and it's nice to know that there are so many different ways to go about doing that with statistics and data in general. Whether it's trying to examine the accuracy of simulation and visualize sampling distributions (mini-project 1), trying to tell a "meaningful story" about the presence of estimators and estimation in the real world (mini-project 2), investigating the effect of sample size on the accuracy of a distribution of confidence intervals -- which can be applied to so many studies out there (mini-project 3), attempting to model the probability of a tennis player winning a point based off of prior knowledge about the players' tendencies (mini-project 4), or convincing somebody that p-values and significance levels are an antiquated and detrimental way of using statistics in the world of research (mini-project 5), statistics holds so much power in anything that we do. So, having a solid understanding of the inner workings of stats (which is what I've gotten from this course and over the course of all the classes I've taken at SLU), is going to be instrumental for me going forward. I suppose what I'm trying to get at is these mini-projects in math stat have shown me how interconnected everything in statistics actually is, which is honestly somewhat different from what I felt going through them one at a time. Upon reflection, when I began the semester, I saw mathematical statistics mostly as just an extension of the theory we developed in probability (which it is...), but now I also see it as way of thinking.
